
spring:
  application:
    name: payment-service # Name of the application; matches configuration in the Config Server
  config:
    import: configserver:http://localhost:8888 # Import configurations from the Config Server
  profiles:
    active: default # Profile to fetch from the Config Server